// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

namespace Polytoria.SourceGen;

[Generator]
public sealed class AssetRegistrationGenerator : IIncrementalGenerator
{
	private const string InstantiableAttributeFullName = "Polytoria.Attributes.InstantiableAttribute";
	private const string BaseAssetFullName = "Polytoria.Datamodel.Resources.BaseAsset";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var assetTypes = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				InstantiableAttributeFullName,
				predicate: static (node, _) => node is ClassDeclarationSyntax,
				transform: static (ctx, _) => GetAssetType(ctx.TargetSymbol as INamedTypeSymbol))
			.Where(static typeName => typeName is not null)
			.Collect();

		context.RegisterSourceOutput(assetTypes, static (spc, types) =>
			spc.AddSource(
				"AssetRegistration.g.cs",
				SourceText.From(GenerateSource(types), Encoding.UTF8)));
	}

	private static string? GetAssetType(INamedTypeSymbol? type)
	{
		if (type is null)
			return null;

		for (var baseType = type.BaseType; baseType is not null; baseType = baseType.BaseType)
		{
			if (baseType.ToDisplayString() == BaseAssetFullName)
				return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
		}

		return null;
	}

	private static string GenerateSource(ImmutableArray<string?> types)
	{
		var typeNames = types
			.OfType<string>()
			.Distinct(StringComparer.Ordinal)
			.OrderBy(static name => name, StringComparer.Ordinal);

		var sb = new StringBuilder();
		using var stringWriter = new StringWriter(sb);
		using var writer = new IndentedTextWriter(stringWriter);

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine();
		writer.WriteLine("namespace Polytoria.Datamodel.Resources;");
		writer.WriteLine();
		writer.WriteLine("public partial class BaseAsset");
		writer.WriteLine("{");
		writer.Indent++;
		writer.WriteLine("internal static void RegisterGeneratedAssetTypes()");
		writer.WriteLine("{");
		writer.Indent++;

		foreach (var typeName in typeNames)
			writer.WriteLine($"RegisterType<{typeName}>();");

		writer.Indent--;
		writer.WriteLine("}");
		writer.Indent--;
		writer.WriteLine("}");

		return sb.ToString();
	}
}
