// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;

namespace Polytoria.SourceGen;

[Generator]
public sealed class TypeRegistryGenerator : IIncrementalGenerator
{
	private const string InstantiableAttributeFullName = "Polytoria.Attributes.InstantiableAttribute";

	private static readonly DiagnosticDescriptor _duplicateTypeNameRule = new(
#pragma warning disable RS2008 // Enable analyzer release tracking
		id: "PTG0008",
#pragma warning restore RS2008 // Enable analyzer release tracking
		title: "Conflicting instantiable type name",
		messageFormat: "Instantiable class name '{0}' is already used by '{1}'; type registry keys must be unique",
		category: "Polytoria.SourceGen",
		defaultSeverity: DiagnosticSeverity.Error,
		isEnabledByDefault: true);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var instantiableTypes = context.SyntaxProvider
			.ForAttributeWithMetadataName(
				InstantiableAttributeFullName,
				predicate: static (node, _) => node is ClassDeclarationSyntax,
				transform: static (ctx, _) =>
				{
					var type = (INamedTypeSymbol)ctx.TargetSymbol;
					return new TypeEntry(
						type.Name,
						type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
						type.Locations.FirstOrDefault() ?? Location.None);
				})
			.Collect();

		context.RegisterSourceOutput(instantiableTypes, static (spc, types) =>
		{
			foreach (var duplicate in types
				.GroupBy(static entry => entry.Name, StringComparer.Ordinal)
				.Where(static g => g.Skip(1).Any()))
			{
				TypeEntry first = duplicate.First();
				string others = string.Join("', '", duplicate.Skip(1).Select(static e => e.FullTypeRef));
				spc.ReportDiagnostic(Diagnostic.Create(_duplicateTypeNameRule, first.Location, first.Name, others));
			}

			spc.AddSource(
				"TypeRegistry.g.cs",
				SourceText.From(GenerateSource(types), Encoding.UTF8));
		});
	}

	private static string GenerateSource(ImmutableArray<TypeEntry> entries)
	{
		var typeEntries = entries
			.GroupBy(static entry => entry.FullTypeRef, StringComparer.Ordinal)
			.Select(static group => group.First())
			.OrderBy(static entry => entry.FullTypeRef, StringComparer.Ordinal);

		var sb = new StringBuilder();
		using var stringWriter = new StringWriter(sb);
		using var writer = new IndentedTextWriter(stringWriter);

		writer.WriteLine("// <auto-generated/>");
		writer.WriteLine("#nullable enable");
		writer.WriteLine("using System;");
		writer.WriteLine("using System.Collections.Generic;");
		writer.WriteLine();
		writer.WriteLine("namespace Polytoria.Datamodel;");
		writer.WriteLine();
		writer.WriteLine("internal static class TypeRegistry");
		writer.WriteLine("{");
		writer.Indent++;
		writer.WriteLine("public static readonly Dictionary<string, Type> InstantiableTypes = new()");
		writer.WriteLine("{");
		writer.Indent++;

		foreach (var entry in typeEntries)
			writer.WriteLine($"{{ \"{entry.Name}\", typeof({entry.FullTypeRef}) }},");

		writer.Indent--;
		writer.WriteLine("};");
		writer.Indent--;
		writer.WriteLine("}");

		return sb.ToString();
	}

	private readonly struct TypeEntry(string name, string fullTypeRef, Location location)
	{
		public readonly string Name = name;
		public readonly string FullTypeRef = fullTypeRef;
		public readonly Location Location = location;
	}
}
